version: '2'
services:
  wireguard-auth:
    #build: ./
    image: bugfan/wireguard-auth
    restart: always
    environment:
      - DES_KEY=12345678  # 8 bytes
      - DB_HOST=10.128.0.3:3305
    logging: 
      driver: "json-file"
      options: 
        max-size: "100m"
    # volumes:
    #   - ./config:/opt/config
    ports:
      - "5000:8005"


  mysql:
    image: mysql/mysql-server:5.6
    # restart: always
    command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_general_ci',
            ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth
    container_name: docker-mysql-auth
    ports:
    - 3305:3306
    volumes:
      -  ./data:/var/lib/mysql
      - ./mysql/config/init:/docker-entrypoint-initdb.d/