version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.6
    # restart: always
    command: [
            '--character-set-server=utf8',
            '--collation-server=utf8_general_ci',
            ]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: auth
    container_name: docker-mysql-auth
    ports:
    - 3305:3306
    networks:
      default:
    volumes:
      -  /var/lib/docker-mysql3-auth/data:/var/lib/mysql
      - ./mysql/config/init:/docker-entrypoint-initdb.d/